-- file: C:\Users\Julien\AppData\Local\nvim\lua\my-config\keys\keys2.lua
return {
  
  -- ["g"] = { nx = "do_g_prefix" },
  -- ["K"] = { nox = "mo_goto_mark"}, -- todo
  -- ["t,"] = { nox = "mo_prev_jump_list" }, -- Go to previous jump list (Ctrl+O)
  -- ["t."] = { nox = "mo_next_jump_list" }, -- Go to next jump list (Ctrl+I)
  -- ["t"] = { nox = "prefix_motion_menu" },
  -- ["t<"] = { nox = "mo_prev_change_list" }, -- Go to previous change list (g;)
  -- ["t>"] = { nox = "mo_next_change_list" }, -- Go to next change list (g,)
  -- ["te"] = { nox = "mo_till_pair" },
  -- ["tF"] = { nox = "do_scroll_up_1" }, -- Scroll screen up by 1 line
  -- ["tf"] = { nox = "do_scroll_up_3" }, -- Scroll screen up by 3 lines
  -- ["tp"] = { nox = "mo_last_jump" }, -- Jump to last jump (``)
  -- ["tS"] = { nox = "do_scroll_down_1" }, -- Scroll screen down by 1 line
  -- ["ts"] = { nox = "do_scroll_down_3" }, -- Scroll screen down by 3 lines
  -- ["ty"] = { nox = "mo_last_insert" }, -- Jump to last insert (`.)
  ["."] = { nx = "do_repeat_last_cmd" },
  ["<"] = { nx = "verb_unindent" },
  ["<A-down>"] = { inotvx = "sys_window_down" },
  ["<A-f>"] = { inotvx = "mo_up" },
  ["<A-left>"] = { inotvx = "sys_window_left" },
  ["<A-p>"] = { inotvx = "sys_next_buffer" },
  ["<A-r>"] = { inotvx = "mo_left" },
  ["<A-right>"] = { inotvx = "sys_window_right" },
  ["<A-s>"] = { inotvx = "mo_down" },
  ["<A-t>"] = { inotvx = "mo_right" },
  ["<A-up>"] = { inotvx = "sys_window_up" },
  ["<A-w>"] = { inotvx = "sys_previous_buffer" },
  ["<C-a>"] = { intvx = "do_select_all" },
  ["<C-c>"] = { intvx = "verb_copy" },
  ["<C-s>"] = { inotvx = "do_save_file" },
  ["<C-v>"] = { cinotvx = "do_paste" },
  ["<C-x>"] = { intvx = "verb_cut" },
  ["<C-z>"] = { intvx = "do_undo" },
  ["<M-O>"] = { i = "do_newline_insert_before" },
  ["<M-o>"] = { i = "do_newline_insert" },
  ["<M-q>"] = { i = "do_comment_line" },
  ["<M-W>"] = { i = "do_redo" },
  ["<M-w>"] = { i = "do_undo" },
  [">"] = { nx = "verb_indent" },
  ["A"] = { n = "do_copy_eol" },
  ["a"] = { nxo = "verb_copy" },
  ["b"] = { n = "do_delete_char" },
  ["B"] = { n = "do_replace_mode" },
  ["C"] = { nox = "do_nothing" },
  ["c"] = { nox = "prefix_mini_surround" },
  ["ca"] = { nox = "mini_surround_add" },
  ["cr"] = { nox = "mini_surround_replace" },
  ["ch"] = { nox = "mini_surround_highlight" },
  ["cm"] = { nox = "mini_surround_last" },
  ["cn"] = { nox = "mini_surround_next" },
  ["cs"] = { nox = "mini_surround_delete" },
  ["D"] = { n = "do_delete_eol" },
  ["d"] = { nx = "verb_delete" },
  ["e"] = { nxo = "mo_find_pair" },
  ["F"] = { nox = "mo_ts_find" },
  ["f"] = { nx = "do_ts_select" },
  ["I"] = { n = "do_insert_bol" },
  ["i"] = { n = "do_insert", x = "op_inner" },
  ["J"] = { n = "do_play_macro" },
  ["j"] = { n = "do_record_macro" },
  ["k"] = { nx = "do_set_mark" },
  ["l"] = { nox = "mo_matching_pair" }, -- Jump to matching pair (%)
  ["m,"] = { nox = "mo_repeat_rfind" },
  ["m."] = { nox = "mo_last_change" }, -- Jump to last change (`")
  ["M"] = { nox = "do_nothing" },
  ["m/"] = { nox = "mo_prev_match" },
  ["mit"] = { nox = "mo_bol_nonblank" },
  ["mo"] = { nxo = "mo_rtill_char" },
  ["mt"] = { nox = "mo_bol" },
  ["mu"] = { nxo = "mo_rfind_char" },
  ["mw"] = { nox = "mo_prev_start_of_word" },
  ["myt"] = { nox = "mo_bol" },
  ["N"] = { nox = "do_nothing" },
  ["n,"] = { nox = "mo_repeat_find" },
  ["n/"] = { nox = "mo_next_match" },
  ["net"] = { nox = "mo_eol" },
  -- todo nt and nyt
  ["no"] = { nox = "mo_till_char" },
  ["nu"] = { nox = "mo_find_char" },
  ["new"] = { nox = "mo_end_of_word" },
  ["nw"] = { nox = "mo_start_of_word" },
  ["O"] = { nx = "do_newline_insert_before" },
  ["o"] = { nx = "do_newline_insert" },
  ["p"] = { nox = "do_nothing" },
  ["P"] = { nox = "do_nothing" },
  ["Q"] = { nx = "do_comment_line" },
  ["q"] = { nx = "verb_comment" },
  ["R"] = { n = "do_change_eol" },
  ["r"] = { nx = "verb_change" },
  ["S"] = { n = "do_cut_eol" },
  ["s"] = { nx = "verb_cut" },
  ["T"] = { nx = "do_select_line" },
  ["t"] = { nx = "verb_select" },
  ["U"] = { nox = "do_nothing" },
  ["u"] = { nox = "mo_jump_to_line" },
  ["V"] = { n = "do_paste_before" },
  ["v"] = { n = "do_paste" },
  ["W"] = { n = "do_redo" },
  ["w"] = { n = "do_undo" },
  ["x"] = { nx = "do_nothing" },
  ["X"] = { nx = "do_nothing" },
  ["Y"] = { n = "do_append_eol" },
  ["y"] = { n = "do_append", xo = "op_around" },
  ["z"] = { nx = "do_z_prefix" },
}
