-- file: C:\Users\Julien\AppData\Local\nvim\lua\my-config\keys\keys_obj.lua
return {
  ["b"] = {    obj = "a_block",  },
  ["c"] = {    obj = "a_condition",  },
  ["F"] = {    obj = "a_function_call",  },
  ["f"] = {    obj = "a_function",  },
  ["g"] = {    obj = "do_g_prefix",  },
  ["i"] = {    obj = "op_inner",  },
  ["L"] = {    obj = "op_prev_end",  },
  ["l"] = {    obj = "op_prev_start",  },
  ["N"] = {    obj = "op_next_end",  },
  ["n"] = {    obj = "op_next_start",  },
  ["p"] = {    obj = "a_paragraph",  },
  ["Q"] = {    obj = "a_comment_block",  },
  ["q"] = {    obj = "a_comment",  },
  ["r"] = {    obj = "a_loop",  },
  ["s"] = {    obj = "op_surround",  },
  ["t"] = {    obj = "a_type",  },
  ["v"] = {    obj = "a_variable",  },
  ["W"] = {    obj = "a_WORD",  },
  ["w"] = {    obj = "a_word",  },
  ["y"] = {    obj = "op_around",  },
  ["z"] = {    obj = "do_z_prefix",  },
}
