-- file: C:\Users\Julien\AppData\Local\nvim\lua\my-config\keys\keys_go.lua
return {
  ["b"] = {    go = "a_block",  },
  ["c"] = {    go = "a_condition",  },
  ["F"] = {    go = "a_function_call",  },
  ["f"] = {    go = "a_function",  },
  ["L"] = {    go = "op_prev_end",  },
  ["l"] = {    go = "op_prev_start",  },
  ["m"] = {    go = "m_jump_to_mark",  },
  ["N"] = {    go = "op_next_end",  },
  ["n"] = {    go = "op_next_start",  },
  ["p"] = {    go = "a_paragraph",  },
  ["Q"] = {    go = "a_comment_block",  },
  ["q"] = {    go = "a_comment",  },
  ["r"] = {    go = "a_loop",  },
  ["s"] = {    go = "mo_matching_char",  },
  ["t"] = {    go = "a_type",  },
  ["v"] = {    go = "a_variable",  },
  ["W"] = {    go = "a_word",  },
  ["w"] = {    go = "a_word",  },
}
