-- file: C:\Users\Julien\AppData\Local\nvim\lua\my-config\keys\keys2.lua
return {
  [","] = { nx = "mo_repeat_rfind" },
  ["."] = { nx = "mo_repeat_find" },
  [";"] = { nx = "do_repeat_last_cmd" },
  ["<"] = { nx = "verb_unindent" },
  [">"] = { nx = "verb_indent" },
  ["A"] = { nx = "do_select_line" },
  ["a"] = { nx = "verb_select" },
  ["B"] = { n = "do_replace_mode" },
  ["b"] = { n = "do_delete_char" },
  ["C"] = { n = "do_copy_eol" },
  ["c"] = { nx = "verb_copy" },
  ["D"] = { n = "do_delete_eol" },
  ["d"] = { nx = "verb_delete" },
  ["E"] = { nx = "verb_go_prev" },
  ["e"] = { x = "verb_go", n = "verb_go_next" },
  ["f"] = { nox = "mo_up" },
  ["g"] = { nx = "do_g_prefix" },
  ["h"] = { nxo = "mo_prev_match" },
  ["I"] = { n = "do_insert_bol" },
  ["i"] = { n = "do_insert", x = "op_inner" },
  ["J"] = { n = "do_play_macro" },
  ["j"] = { n = "do_record_macro" },
  ["k"] = { nxo = "mo_next_match"   },
  ["L"] = { nx = "mo_rfind_char" },
  ["l"] = { nx = "mo_find_char" },
  ["m"] = { nx = "do_set_mark" },
  ["N"] = { n = "do_change_eol" },
  ["n"] = { nx = "verb_change" },
  ["Q"] = { n = "do_comment_line" },
  ["q"] = { n = "verb_comment" },
  ["R"] = { nox = "mo_screen_top" },
  ["r"] = { nox = "mo_left" },
  ["s"] = { nox = "mo_down" },
  ["T"] = { nox = "mo_screen_bottom" },
  ["t"] = { nox = "mo_right" },
  ["U"] = { nx = "mo_ultra_rfind" },
  ["u"] = { nx = "mo_ultra_find" },
  ["V"] = { n = "do_paste_before" },
  ["v"] = { n = "do_paste" },
  ["W"] = { n = "do_redo" },
  ["w"] = { n = "do_undo" },
  ["X"] = { n = "do_cut_eol" },
  ["x"] = { nx = "verb_cut" },
  ["Y"] = { n = "do_append_eol" },
  ["y"] = { x = "op_around", n = "do_append" },
  ["z"] = { nx = "do_z_prefix" },
  ["<A-f>"] = { inotvx = "sys_window_up" },
  ["<A-p>"] = { inotvx = "sys_next_buffer" },
  ["<A-r>"] = { inotvx = "sys_window_left" },
  ["<A-s>"] = { inotvx = "sys_window_down" },
  ["<A-t>"] = { inotvx = "sys_window_right" },
  ["<A-w>"] = { inotvx = "sys_previous_buffer" },
  ["<C-a>"] = { intvx = "do_select_all" },
  ["<C-c>"] = { intvx = "verb_copy" },
  ["<C-s>"] = { inotvx = "do_save_file" },
  ["<C-v>"] = { cinotvx = "do_paste" },
  ["<C-x>"] = { intvx = "verb_cut" },
  ["<C-z>"] = { intvx = "do_undo" },
}
